USE customer_behavior;
-- Q1 What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchased_amount) AS revenue
FROM customer
GROUP BY gender;

-- Q2 Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchased_amount
FROM customer
WHERE
    (SELECT AVG(purchased_amount) AS average_amount
	 FROM customer)
<= purchased_amount AND discount_applied = 'Yes';

-- Q3 Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating), 2) AS average_ratings
FROM customer
GROUP BY item_purchased
ORDER BY average_ratings DESC
LIMIT 5;

-- Q4 Compare the average purchase amounts between standard and express shipping.
SELECT shipping_type, ROUND(AVG(purchased_amount), 2) AS average_amount
FROM customer
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type;

-- Q5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
AVG(purchased_amount) AS average_spend,
SUM(purchased_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;

-- Q6 Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7 Segment customers into new, returning, and loyal based on their total number of previous
-- purchases, and show the count of each segment.
WITH cte AS
(
	SELECT
	previous_purchases,
	CASE
		WHEN previous_purchases = 1 THEN 'New'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyal'
	END AS customer_segment
	FROM customer
)
SELECT
customer_segment, COUNT(customer_segment) AS Num_of_customers
FROM cte
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
WITH cte AS
(
	SELECT
	category, item_purchased,
    COUNT(customer_id) AS NumOfOrders,
	ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS rnk
	FROM customer
    GROUP BY category, item_purchased
)
SELECT
rnk, category, item_purchased, NumOfOrders
FROM cte
# WHERE rnk IN (1, 2, 3)
WHERE rnk <= 3;

-- Q9 Are customers who are repeat buyers (More than 5 previous purchases) also likely to subscribe?
SELECT
subscription_status, COUNT(customer_id) AS NumOfCustomers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?
SELECT
age_group, SUM(purchased_amount) AS revenue
FROM customer
GROUP BY age_group
ORDER BY revenue DESC;




